So I received a large volume of demonic dreams and visions through the night
including dreams that oppose my being made a new creation.

I do however recall something in my sleep where I was reciting from John 11:25-27.

I have complained at the immense satanic oppression which I have been experiencing, and I have also mentioned that I feel as though I was oppressed before I was born-again. And after I have been born-again I have endeavoured to be wise for what is good and innocent as to what is evil. And in discerning such things and making my opinion known, I have received so much demonic harassment that is opposed to me being a new creation in Christ Jesus.

Now I say with confidence that I have been made new, given a new soul, and while that happened, I called out to Jesus to save me.
And I also believe that by faith in Jesus Christ, I have the right to become a child of God and to call God my father as opposed to anyone else.

I'm very tired of the satanic resistance I have been getting as people oppose my confessions of faith.

When I got born-again all things became new. There is only an apparent history before I was born-again. All things have become new. But people who walk in the flesh and against the truth have been opposing that, including the person who I used to refer to as "Dad", and I'm quite frankly sick of this bizarre and downright unhealthy situation that I find myself in at the residental address at which I have been sleeping, and various other circumstances, such as no references, and no-one really making open professions of faith to me that are exactly the testimony in I John 4:2. I'm really sick of it. I want to know who my true family in Christ are.

I do not want slanderous lies coming from people who are rejecting the truth spreading misleading information to others so as to deter them from putting their faith in Jesus Christ. Because if people say to others what is false about me, telling others I have said things which I didn't really say, when I'm confessing to the truth of God, then it's really bearing false testimony about God and trying to deter people from trusting in Jesus. And I'm concerned about that possibly happening as these heinous situations play out in the confrontations with the person who I no longer refer to as "Dad", the man on earth who thinks from the flesh and denies the truth that "if any man be in Christ, new creation". Now God willing, God will find me in Christ, and I endeavour to be. May Jesus Christ exercise His might and get me out of these chains of darkness.

I'm really tired of ongoing demonic harassment and general oppression, and the extreme lack of assistance to help in the specific way in which I ask
by the so-called church. If I need X and someone gives me Y that is very similar to how people gave Jesus vinegar after He said that He thirsted.
What's Jesus supposed to do with vinegar, put it on a Caesar salad? It would've made sense to give Jesus water because He said that He was thirsty.
I want to hear the testimony of Jesus Christ from people which confesses that He is the Word made flesh, come into the world from God, that He died on a tree and rose from the dead and ate a broiled fish. I want to hear confessions to the truth about Jesus. Otherwise, I wont be able to whole heartedly confess them before Father God.

And I would also very much like references so that I can get some employment.
I've been getting some very intense spiritual attacks against my soul. One of the worst things is this sexual defilement thing.
I feel like what has been going on with my salvation has been so strongly opposed by satan and by the flesh and by the spirit of the world that it is palpably impacting my soul.

I have seen different sides to this person who I no longer refer to as Dad, since I now call God my Dad, God who is my one and only and true Father.
The different sides to him, that is the person on earth who I no longer refer to as Dad, are one who seems to agree with God's word, and one who seems to reject it.

If someone asks me if he's born of God, then I would say, please either him himself what he thinks of Jesus and His word, to determine if he is in agreement with Jesus and His word, or ask Father God if God thinks he is born of God,
because to be born-of-God is to agree with God, and to love in the same was as God, to love in the truth.

** 2:21pm

Unsure what to say except that the demonic harassment has been quite intense, and the devil has been trying to keep me ensnared.
Truly disgusting stuff. The Lord Jesus Christ hasn't seemingly been protecting me. I've been born-again, and in a big way Jesus has certainly set me free from sin.
But what has happened to me since then has been so incredibly disgusting spiritually. My God, Father God and Jesus Christ the Son of God who He has sent, Yeshua Hamashiach, Holy Spirit, Yahweh, Almighty God, God of Abraham, Isaac and Jacob, why is this happening?
Why have I been made to experience such disgusting spiritual defilement from seemingly every direction.
I'm sick of it. It's abuse. What I've been experiencing is not discipline, that is for certain. The spirit of sexual uncleanness which to my despair I still have felt throughout the day affecting my genitals, the threat in the morning coming from that man on earth who I am instructed to not call father, the demonic dreams (there was even one I recall speaking againt the name of Yeshua), the spirit of LGBT which this city of Dunedin seems to have been absolutely infested with (I want to speak to this that I do not believe that endorsing sexual immorality and adultery is within the freedoms which are found in Christ Jesus). All of this activity is absolutely satanic.

Let me document some demonic activity which I just witnessed I was sitting writing in my journal on the street about 30 minutes ago.
Firstly, along the way to where I ended up going, I bumped into a guy who asked me how I was, and so I described the unhealthy situation at the place I have been sleeping, and I described how I've been born-again, and he very quickly brought into the conversation that we have to "find our own selves", and I mentioned back to him that I believe that God is my Dad and that the freedom in Christ is freedom within the "system". The freedom in Christ is freedom within Christ's teachings. So far, so good, in my view. OK, so then I walk down to the street, and I sit down on the bench.
So I'm then sitting down praying (I like to write out prayers sometimes on paper) on a bench on the main street.
I'm sitting outside of an overtly pro-LGBT cafe. And someone walks up to me who was sitting on the other side of the road (not from this cafe) and just starts yelling at me telling me to stop slandering me for saying he likes women, also saying that he doesn't like women. And I prayed for this man, and I pray that God heals him and delivers him from demons, and likewise I prayed to God that God would deliver me from demonic harassment, and that God would heal our souls, in Jesus Christ's name. And a young lady witnessing this walks out of the cafe afterwards and asks if I'm OK, and that was a very nice gesture, and I appreciate that, that is not at all what I take issue with. It was a very nice gesture. But the issue is that I have been getting attacked by a spirit trying to goad me towards not only reneging on my committments to the Lord Jesus Christ (i.e. by giving me marriage related dreams, etc.), and into endorsing sexual immorality, endorsing LGBT, etc.
Whatever has been generally trying to push me into this stuff is really disgusting. I want to be brought out of it, and I want to be able to walk according to Jesus Christ's teachings, according to Yeshua Hamashiach's teachings, according to the teachings of Jesus Christ who is Yahweh and who is the Son of God. I want to be able to walk according to the teachings of Christ in freedom, and I want to have fellowship with family in Christ.

What a disgusting situation I find myself in. May God step in and deliver me from this disgusting filth that has been sent against me.
If God cares at all for my spiritual wellbeing then He will surely protect my soul instead of let me get attacked by this disgusting filth.
In Jesus Christ's name.

And may those who had reckoned that they knew before I was born-again come to know Jesus Christ for themself and come to love Jesus Christ to walk according to Jesus Christ's teachings for themself.
Even people who did not consider themselves to be Christian. I hope that if they come to walk in the light, to love the truth of God, that in doing so, I will see them again, God willing. If both myself and someone else walk in the light, according to the teaching of Christ, and keep doing so, I believe that we will come to have fellowship with one another (I John 1:7).
It's not right for me to refer to someone as "friend" or "brother" who had only previously known me as "friend" or "brother" since before I was born-again.

Proverbs 17:17 - A friend loves at all times, and a brother is born for adversity.
1 Peter 5:8-9 - Be sober-minded and alert. Your adversary the devil prowls around like a roaring lion, seeking someone to devour. Resist him, standing firm in your faith and in the knowledge that your brothers throughout the world are undergoing the same kinds of suffering.

** Keeping Jesus' word is believing (faithing) in Jesus

#+BEGIN_QUOTE
  *John 3:14-21* - `And as Moses did lift up the serpent in the wilderness, so it behoveth the Son of Man to be lifted up, that every one who is believing in him may not perish, but may have life age-during, for God did so love the world, that His Son--the only begotten--He gave, that every one who is believing in him may not perish, but may have life age-during. For God did not send His Son to the world that he may judge the world, but that the world may be saved through him; he who is believing in him is not judged, but he who is not believing hath been judged already, because he hath not believed in the name of the only begotten Son of God. `And this is the judgment, that the light hath come to the world, and men did love the darkness rather than the light, for their works were evil; for every one who is doing wicked things hateth the light, and doth not come unto the light, that his works may not be detected; but he who is doing the truth doth come to the light, that his works may be manifested, that in God they are having been wrought.' (YLT)
#+END_QUOTE

#+BEGIN_QUOTE
  *John 8:31-32,37,45-47,51* - So Jesus said to the Jews who had believed in him, If you abide in my word, you are truly my disciples, and you will know the truth, and the truth will set you free. I know that you are offspring of Abraham; yet you seek to kill me because my word finds no place in you. But because I tell the truth, you do not believe me. Which one of you convicts me of sin? If I tell the truth, why do you not believe me? Whoever is of God hears the words of God. The reason why you do not hear them is that you are not of God. Truly, truly, I say to you, if anyone keeps my word, he will never see death. (ESV)
#+END_QUOTE

** May God set me free from the snare (G3803 pagida) of the devil

I know I have been set free from sin when I was born-again of the spirit and baptized into Christ's death, but please set me free some more because Satan has been attacking me and set his trap to try to keep me bound in the flesh. Satan has tried to pull me into committing sin again. I blame this at least in part to being prevented from marrying, but also because the churches have been not preaching the true gospel of Jesus Christ, and also because of the destruction of employment opportunity by the normalisation of theft through AI. The churches in this city in which I dwell and all around the world have been avoiding teaching people the actual words of Jesus Christ.

#+BEGIN_QUOTE
  *John 8:34-36* - Jesus answered them, Truly, truly, I say to you, everyone who commits sin is a slave to sin. The slave does not remain in the house forever; the son remains forever. So if the Son sets you free, you will be free indeed. (ESV)
#+END_QUOTE
