* Jesus probably never married to a woman while He was in the flesh this Earth
Hebrews 11:39: And all these, having gained approval through their faith, did not receive what was promised,
Hebrews 11:40: because God had provided something better for us, so that apart from us they would not be made perfect.

Matthew 22:30: For in the resurrection they neither marry nor are given in marriage, but are like angels in heaven.
Mark 12:25: For when they rise from the dead, they neither marry nor are given in marriage, but are like angels in heaven.

Matthew 26:29: I tell you I will not drink again of this fruit of the vine until that day when I drink it new with you in my Father's kingdom.
Mark 14:25: Truly, I say to you, I will not drink again of the fruit of the vine until that day when I drink it new in the kingdom of God.
Luke 22:18: For I tell you that from now on I will not drink of the fruit of the vine until the kingdom of God comes.

But he is married/to be married to His bride, the Church.

Matthew 9:15: And Jesus said to them, Can the wedding guests mourn as long as the bridegroom is with them? The days will come when the bridegroom is taken away from them, and then they will fast.
Matthew 25:1: Then the kingdom of heaven will be like ten virgins who took their lamps and went to meet the bridegroom.
Matthew 25:5: As the bridegroom was delayed, they all became drowsy and slept.
Matthew 25:6: But at midnight there was a cry, Here is the bridegroom! Come out to meet him.
Matthew 25:10: And while they were going to buy, the bridegroom came, and those who were ready went in with him to the marriage feast, and the door was shut.
Mark 2:19: And Jesus said to them, Can the wedding guests fast while the bridegroom is with them? As long as they have the bridegroom with them, they cannot fast.
Mark 2:20: The days will come when the bridegroom is taken away from them, and then they will fast in that day.
Luke 5:34: And Jesus said to them, Can you make wedding guests fast while the bridegroom is with them?
Luke 5:35: The days will come when the bridegroom is taken away from them, and then they will fast in those days.
John 2:9: When the master of the feast tasted the water now become wine, and did not know where it came from (though the servants who had drawn the water knew), the master of the feast called the bridegroom
John 3:29: The one who has the bride is the bridegroom. The friend of the bridegroom, who stands and hears him, rejoices greatly at the bridegroom's voice. Therefore this joy of mine is now complete.
Revelation of John 18:23: and the light of a lamp will shine in you no more, and the voice of bridegroom and bride will be heard in you no more, for your merchants were the great ones of the earth, and all nations were deceived by your sorcery.
Revelation of John 19:7: Let us rejoice and exult and give him the glory, for the marriage of the Lamb has come, and his Bride has made herself ready;
Revelation of John 21:2: And I saw the holy city, new Jerusalem, coming down out of heaven from God, prepared as a bride adorned for her husband.
Revelation of John 21:9: Then came one of the seven angels who had the seven bowls full of the seven last plagues and spoke to me, saying, Come, I will show you the Bride, the wife of the Lamb.
Revelation of John 22:17: The Spirit and the Bride say, Come. And let the one who hears say, Come. And let the one who is thirsty come; let the one who desires take the water of life without price.
