#+TITLE: New Testament Greek study
#+AUTHOR: Shane Mulligan
#+DATE: <2024-10-19 Sat>
#+KEYWORDS: faith christianity

#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+OPTIONS: toc:nil

#+LATEX_COMPILER: xelatex

* NT Greek study

** Question

I'd like to understand the Greek behind the phrase =in the teaching of Christ=.
Because I'm interested in whether the phrase =teaching of Christ= refers to the teachings that Christ
taught including His teachings before His death, burial and resurrection, or
if it the phrase is also talking about the doctrine surrounding what is known about Christ.
My guess is both, but I'd like to understand the Greek a bit better.

#+BEGIN_QUOTE
  *II John 1:9* - Everyone who goes on ahead and does not abide =in the teaching of Christ=, does not have God. Whoever abides in the teaching has both the Father and the Son. (ESV)
#+END_QUOTE

** Case

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  interrogative
      /ˌɪntəˈrɒɡətɪv/
      adjective
      having the force of a question.
      "a hard, interrogative stare"

  transitive verb
      A verb that entails one or more transitive
      objects, for example, 'enjoys' in Amadeus
      enjoys music.

      This contrasts with intransitive verbs,
      which do not entail transitive objects,
      for example, 'arose' in Beatrice arose.
#+END_SRC

Notes from https://en.wikipedia.org/wiki/Grammatical_case:

- *N (Nominative)*
  - =Indicates=: Subject of a finite verb
  - =Sample case words=: we
  - =Sample sentence=: _We_ went to the store.
  - =Interrogative=: Who or what?
  - =Notes=: Corresponds to English's subject pronouns.
- *V (Vocative)*
  - =Indicates=: Addressee
  - =Sample case words=: John
  - =Sample sentence=:
    - _John_, are you all right?
    - Hello, _John_!
    - O John, how are you! (archaic)
  - =Interrogative=: 
  - =Notes=: Roughly corresponds to the archaic use of "O" in English.
- *A (Accusative)*
  - =Indicates=: Direct object of a transitive verb
  - =Sample case words=: us, for us, the (object)
  - =Sample sentence=:
    - The clerk remembered _us_.
    - John waited _for us_ at the bus stop.
    - Obey _the law_.
  - =Interrogative=: 
    - Whom or what?
  - =Notes=: Corresponds to English's object pronouns and preposition for construction before the object, often marked by a definite article the. Together with dative, it forms modern English's oblique case.
- *G (Genitive)*
  - =Indicates=: 
  - =Sample case words=: 
  - =Sample sentence=: 
  - =Interrogative=: 
  - =Notes=: 
- *D (Dative)*
  - =Indicates=: 
  - =Sample case words=: 
  - =Sample sentence=: 
  - =Interrogative=: 
  - =Notes=: 

*** Example
https://biblehub.com/interlinear/2_john/1-9.htm

#+BEGIN_SRC text -n :async :results verbatim code :lang text
  tou
  3588
  tou
  τοῦ
   -
  Art-GMS
#+END_SRC

- G - [[https://en.wikipedia.org/wiki/Grammatical_case][Genitive]]
- M - [[https://en.wikipedia.org/wiki/Grammatical_case][Masculine]]
- S - [[https://en.wikipedia.org/wiki/Grammatical_case][Singular]]
