* Journal
** <2024-10-20 Sun>
My earliest memories are of living in Miramar before Weta Workshop.
Today at C3 Church, the pastor took an analogy from Lord of the Rings to describe sin.
What Frodo may have experienced in fiction, carrying the one ring, reminds me of my experience over the last 2 years.
In the books, the ring amplifies evil. The ring turned Sméagol into Gollum.
That's like what sin does to people - it corrupts people and the effects are:
- they are corrupted from the image of God.
- blindness to their condition, death.

People are born with corruption, but as people turn away from the truth and commit sin the corruption magnifies. It doesn't get better.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%206%3A23&version=ESV][Romans 6:23]]* - For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord. (ESV)
#+END_QUOTE

Corruption gets increasingly worse without atonement by blood.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Hebrews%209%3A22&version=ESV][Hebrews 9:22]]* - Indeed, under the law almost everything is purified with blood, and *without the shedding of blood there is no forgiveness of sins*. (ESV)
#+END_QUOTE

Jesus said in [[https://www.biblegateway.com/passage/?search=Matthew%2023%3A26&version=ESV][Matthew 23:26]] (from the ESV), "You blind Pharisee! First clean the inside of the cup and the plate, that the outside also may be clean."
We really don't want corruption in our heart or impurity in our spirit. The outside reflects what's going on inside us, and I don't mean merely our outward appearance. Dare I confess this but I will for the sake of others so they may take sin seriously, after being born-again as I had been repenting (even after being born-again), I have seen things that have made me feel like in some sense my spiritual innocence has been stolen.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%209%3A6&version=ESV][Genesis 9:6]]* - Whoever sheds the blood of man, by man shall his blood be shed, for God made man in his own image. (ESV)
#+END_QUOTE

While sin corrupts, the grace of God through blood of Jesus can restore us. He is the perfect man, and His blood washes us clean from corruption.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%204%3A4&version=ESV][II Corinthians 4:4]]* - In their case the god of this world has blinded the minds of the unbelievers, to keep them from seeing the light of the gospel of the glory of Christ, who is the image of God. (ESV)
#+END_QUOTE

I just didn't expect that after I was born-again that there was going to be a spiritual battle. But there is a battle, and it hit me fast and hard.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%208%3A13&version=ESV][Romans 8:13]]* - For if you live according to the flesh you will die, but if by the Spirit you put to death the deeds of the body, you will live. (ESV)
#+END_QUOTE

Like traumatised Frodo where Hobbiton was essentially ruined for him, I have among other things asked to be born-again again, and that I can be [[https://meninblack.fandom.com/wiki/Neuralyzer][neuralyzed]] because of what I've been through, or raptured and taken to heaven, everything new. But I'm still here, it seems. At least I've been brought into Christ.

* <2025-02-05 Wed> Journal
** I had a dream conversation with someone
Lots of tall waves going through a town square.
Me clinging to the top of a tall streetlight to withstand the waves.
I talk to a young kid explaining to him what is love.

God loved us first, and we then love.
A crucial part of love is forgiveness.
We forgive because God forgave us first.
God loved us first. God forgave us first.

Then I heard a voice that said, "God says abide in love".
And I thought be rooted and grounded in love.

** I just said this in a dream as a response to a question - it's spiritually inspired, hopefully from God
- Why do we love, We love because God loved us first.
- We forgive because God forgave us first.
- Why are we to be holy? Because God said, "Be holy for I am Holy."

So why do we not want to be dominated by superintelligent AI? Because God designed us to take dominion over the planet, not to be overcome by it.

For those in Christ, we don't seek world domination, but by seeking the kingdom of God and His righteousness, we "overcome the world". And we are sanctified, keeping God's commandments, loving one another in Christ, and coming to the knowledge of the Truth, knowledge of God the Father and God the Son with His Holy Spirit, and receive an inheritance in Christ in heaven. we do that by being found in Christ, we do that by being servants in Christ.

#+BEGIN_QUOTE
  *Mark 8:36* - For what does it profit a man to gain the whole world and forfeit his life? (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *Genesis 1:26* - Then God said, Let us make man in our image, after our likeness. And let them have dominion over the fish of the sea and over the birds of the heavens and over the livestock and over all the earth and over every creeping thing that creeps on the earth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *Acts 20:32* - And now I commend you to God and to the word of his grace, which is able to build you up and to give you the inheritance among all those who are sanctified. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *Ephesians 5:5* - For you may be sure of this, that everyone who is sexually immoral or impure, or who is covetous (that is, an idolater), has no inheritance in the kingdom of Christ and God. (ESV)
#+END_QUOTE

As a born-again Christian, we are to receive an inheritance.

#+BEGIN_QUOTE
  *I Peter 1:3-5* - Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead, to an inheritance that is imperishable, undefiled, and unfading, kept in heaven for you, who by God's power are being guarded through faith for a salvation ready to be revealed in the last time. (ESV)
#+END_QUOTE

+ Quote from John Piper :: "We don't kill to spread our kingdom. We die to spread our kingdom." AMEN!!
