* Journal
** <2024-10-20 Sun>
My earliest memories are of living in Miramar before Weta Workshop.
Today at C3 Church, the pastor took an analogy from Lord of the Rings to describe sin.
What Frodo may have experienced in fiction, carrying the one ring, reminds me of my experience over the last 2 years.
In the books, the ring amplifies evil. The ring turned Sméagol into Gollum.
That's like what sin does to people - it corrupts people and the effects are:
- they are corrupted from the image of God.
- blindness to their condition, death.

People are born with corruption, but as people turn away from the truth and commit sin the corruption magnifies. It doesn't get better.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%206%3A23&version=ESV][Romans 6:23]]* - For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord. (ESV)
#+END_QUOTE

Corruption gets increasingly worse without atonement by blood.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Hebrews%209%3A22&version=ESV][Hebrews 9:22]]* - Indeed, under the law almost everything is purified with blood, and *without the shedding of blood there is no forgiveness of sins*. (ESV)
#+END_QUOTE

Jesus said in [[https://www.biblegateway.com/passage/?search=Matthew%2023%3A26&version=ESV][Matthew 23:26]] (from the ESV), "You blind Pharisee! First clean the inside of the cup and the plate, that the outside also may be clean."
We really don't want corruption in our heart or impurity in our spirit. The outside reflects what's going on inside us, and I don't mean merely our outward appearance. Dare I confess this but I will for the sake of others so they may take sin seriously, after being born-again as I had been repenting (even after being born-again), I have seen things that have made me feel like in some sense my spiritual innocence has been stolen.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%209%3A6&version=ESV][Genesis 9:6]]* - Whoever sheds the blood of man, by man shall his blood be shed, for God made man in his own image. (ESV)
#+END_QUOTE

While sin corrupts, the grace of God through blood of Jesus can restore us. He is the perfect man, and His blood washes us clean from corruption.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=2%20Corinthians%204%3A4&version=ESV][II Corinthians 4:4]]* - In their case the god of this world has blinded the minds of the unbelievers, to keep them from seeing the light of the gospel of the glory of Christ, who is the image of God. (ESV)
#+END_QUOTE

I just didn't expect that after I was born-again that there was going to be a spiritual battle. But there is a battle, and it hit me fast and hard.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%208%3A13&version=ESV][Romans 8:13]]* - For if you live according to the flesh you will die, but if by the Spirit you put to death the deeds of the body, you will live. (ESV)
#+END_QUOTE

Like traumatised Frodo where Hobbiton was essentially ruined for him, I have among other things asked to be born-again again, and that I can be [[https://meninblack.fandom.com/wiki/Neuralyzer][neuralyzed]] because of what I've been through, or raptured and taken to heaven, everything new. But I'm still here, it seems. At least I've been brought into Christ.

** <2025-03-02 Sun>
I received a picture in my sleep (Psa 1).

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%201%3A1-6&version=ESV][Psalms 1:1-6]]* - Blessed is the man who walks not in the counsel of the wicked, nor stands in the way of sinners, nor sits in the seat of scoffers; but his delight is in the law of the LORD, and on his law he meditates day and night. He is like a tree planted by streams of water that yields its fruit in its season, and its leaf does not wither. In all that he does, he prospers. The wicked are not so, but are like chaff that the wind drives away. Therefore the wicked will not stand in the judgment, nor sinners in the congregation of the righteous; for the LORD knows the way of the righteous, but the way of the wicked will perish. (ESV)
#+END_QUOTE

A brother in Christ gave me this yesterday:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=John%2021%3A15-18&version=ESV][John 21:15-18]]* - When they had finished breakfast, Jesus said to Simon Peter, Simon, son of John, do you love me more than these? He said to him, Yes, Lord; you know that I love you. He said to him, Feed my lambs. He said to him a second time, Simon, son of John, do you love me? He said to him, Yes, Lord; you know that I love you. He said to him, Tend my sheep. He said to him the third time, Simon, son of John, do you love me? Peter was grieved because he said to him the third time, Do you love me? and he said to him, Lord, you know everything; you know that I love you. Jesus said to him, Feed my sheep. Truly, truly, I say to you, when you were young, you used to dress yourself and walk wherever you wanted, but when you are old, you will stretch out your hands, and another will dress you and carry you where you do not want to go. (ESV)
#+END_QUOTE

A bunch of other stuff happened but my days are too packed to explain it all.

* <2025-02-05 Wed> Journal
When it comes to dreams I get, I don't trust anything which doesn't confess Jesus, but I will often take them and use them as prompts to do a Bible study, and run things by the Scripture.

** I had a dream conversation with someone
Lots of tall waves going through a town square.
Me clinging to the top of a tall streetlight to withstand waves of water flowing through what looked like a courtyard.
I then talked to a young kid (and I remember seeing a square rainbow) explaining to him what is love.

God loved us first, and we then love.
A crucial part of love is forgiveness.
We forgive because God forgave us first.
God loved us first. God forgave us first.

Then I heard a voice that said, "God says abide in love".
And I thought be rooted and grounded in love.

In the dream, though, the name "Jesus" wasn't confessed at all, and neither was there a call to holiness.

Also I want to stress, that God's grace teaches us to deny ungodliness:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Titus%202%3A11-14&version=ESV][Titus 2:11-14]]* - For the grace of God has appeared, bringing salvation for all people, training us to renounce ungodliness and worldly passions, and to live self-controlled, upright, and godly lives in the present age, waiting for our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ, who gave himself for us to redeem us from all lawlessness and to purify for himself a people for his own possession who are zealous for good works. (ESV)
#+END_QUOTE

** A second dream: I just said this in a dream as a response to a question - it's spiritually inspired, hopefully from God
- Why do we love, We love because God loved us first.
- We forgive because God forgave us first.
- Why are we to be holy? Because God said, "Be holy for I am Holy."

So why do we not want to be dominated by superintelligent AI? Because God designed us to take dominion over the planet, not to be overcome by it.

*** Christians spread our kingdom not through physical force
For those in Christ, we don't seek world domination, but by seeking the kingdom of God and His righteousness through faith in Jesus who is the Christ, the Son of God, we "overcome the world". And we are sanctified, keeping God's commandments, loving one another in Christ, and coming to the knowledge of the Truth, knowledge of God the Father and God the Son with His Holy Spirit, and receive an inheritance in Christ in heaven. we do that by being found in Christ, we do that by being servants in Christ.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Mark%208%3A36&version=ESV][Mark 8:36]]* - For what does it profit a man to gain the whole world and forfeit his life? (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%201%3A26&version=ESV][Genesis 1:26]]* - Then God said, Let us make man in our image, after our likeness. And let them have dominion over the fish of the sea and over the birds of the heavens and over the livestock and over all the earth and over every creeping thing that creeps on the earth. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%2020%3A32&version=ESV][Acts 20:32]]* - And now I commend you to God and to the word of his grace, which is able to build you up and to give you the inheritance among all those who are sanctified. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%205%3A5&version=ESV][Ephesians 5:5]]* - For you may be sure of this, that everyone who is sexually immoral or impure, or who is covetous (that is, an idolater), has no inheritance in the kingdom of Christ and God. (ESV)
#+END_QUOTE

As a born-again Christian, we are to receive an inheritance.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Peter%201%3A3-5&version=ESV][I Peter 1:3-5]]* - Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead, to an inheritance that is imperishable, undefiled, and unfading, kept in heaven for you, who by God's power are being guarded through faith for a salvation ready to be revealed in the last time. (ESV)
#+END_QUOTE

+ Quote from John Piper :: "We don't kill to spread our kingdom. We die to spread our kingdom." AMEN!!

#+BEGIN_QUOTE
  *I Timothy 1:8-11* - But we know that the Law is good, if one uses it lawfully, realizing the fact that law is not made for a righteous person, but for those who are lawless and rebellious, for the ungodly and sinners, for the unholy and profane, for those who kill their fathers or mothers, for murderers and immoral men and homosexuals and kidnappers and liars and perjurers, and whatever else is contrary to sound teaching, according to the glorious gospel of the blessed God, with which I have been entrusted. (NASB)
#+END_QUOTE

** Lastly, I got home and saw the news that Trump is going to the Gaza strip

I just want to say that I believe we should overcome evil with good. Christians should speak and side with the truth in love.

#+BEGIN_QUOTE
  *Romans 12:19-21* - Beloved, never avenge yourselves, but leave it to the wrath of God, for it is written, Vengeance is mine, I will repay, says the Lord. To the contrary, if your enemy is hungry, feed him; if he is thirsty, give him something to drink; for by so doing you will heap burning coals on his head. Do not be overcome by evil, but overcome evil with good. (ESV)
#+END_QUOTE

** Yesterday morning among all the spiritual attack I got, I heard in my sleep
"Our God will be exalted".

But it carried literally no confession of Jesus, so I don't know who or what was speaking to me or who's God it is.

I know "my" God, Jesus, is exalted:

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Isaiah%2033%3A5&version=ESV][Isaiah 33:5]]* - The LORD is exalted, for he dwells on high; he will fill Zion with justice and righteousness, (ESV).
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%205%3A31&version=ESV][Acts 5:31]]* - God exalted him at his right hand as Leader and Savior, to give repentance to Israel and forgiveness of sins. (ESV)
#+END_QUOTE

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Philippians%202%3A9-11&version=ESV][Philippians 2:9-11]]* - Therefore God has highly exalted him and bestowed on him the name that is above every name, so that at the name of Jesus every knee should bow, in heaven and on earth and under the earth, and every tongue confess that Jesus Christ is Lord, to the glory of God the Father. (ESV)
#+END_QUOTE

** More spiritual attack - a diatribe

+ Journal: <2025-03-15 Sat> :: I'm sick and tired of being left undelivered from this defiling spiritual prison which I have been put in, prevented from working and marrying and continually harassed by demons, seeing sides to people I love which I wish I could have totally erased from my memory forever. I am begging You God to make this evil end today. I feel as though there are still demons which are keeping track of the amount of money I have and accusing me and slandering me when I'm trying to obey Jesus to the best of my ability.
  What I have been put through has been a living nightmare.
  This morning yet another day just being harassed by evil dreams and visions being pushed into my head, and this [[https://pastorvlad.org/spiritualspouses/][spirit spouse]] stuff, and the unreasonable amount of being put on trial.
  If it's not an actual courthouse then it's demons challenging me through various people over extreme scrutiny of my obedience to Jesus.
  While I am continually "ghosted" by people going silent on me - it's absolutely satanic stuff.
  It's been well over 2 years of this type of torment now, almost exactly daily.
  The events surrounding me being born-again of the Spirit are pure abomination.
  There's things I have witnessed that are unspeakably dark and scar my memory.
  I wish that God would make me born-again again whilst erasing my memories and ensure the types of things I have been through would never recur in this life or the next.
  I feel like my redemption is the most compromised botched-job redemption in the history of mankind.
  It's a living and enduring hell on earth which I've been going though - spiritually.
  In the material, NZ is pretty OK, but spiritually I'm being put through hell making the events of 2020-2021 regarding the covid pandemic and lockdowns look like nothing.
  But I know the Christians in Syria, for example, are suffering terribly - I can't imagine how awful it would be for them.
  But it's no consolation to me to be allowed to go on living in this world.
  I'd definitely rather not be here in this world.
  Is it too much to ask of God to be delivered from almost continual demonic harassment?
  I assume that [[https://www.biblegateway.com/passage/?search=2%20Corinthians%2012%3A9&version=ESV][II Corinthians 12:9]]'s "My grace is sufficient for you" does not apply.
  How can anyone function when the joy of being clean, being saved, or being able to help people in need or being able to have a wife or family is taken away?
  What has continued harassing me and trying to destroy my life is disgusting.
  To practice righteousness is a right given to people who trust in Jesus' name so I consider to not
  be able to do so to be a violation of my right in believing in Jesus
  and to be prevented from doing so is antichrist.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Psalms%20109%3A21&version=ESV][Psalms 109:21]]* - But you, O GOD my Lord, deal on my behalf for your name's sake; because your steadfast love is good, deliver me! (ESV)
#+END_QUOTE
