*** Woman pastors (Heavenly Minded Home ministry)
I've copied most of Heavenly Minded Home's transcript here for this video.
It's really sound and helpful teaching from Heidi, a pastor's wife who is running this ministry.
Thanks Heidi.

+ [[https://www.youtube.com/watch?v=9PDW0ka8_T0][youtube.com: What the Bible REALLY Says About Women as Church Leaders {@HeavenlyMindedHome}]] :: I commented: Thank you. I am in essentially full agreement with this, and thanks for this. I'm recently born again and God has been teaching me and testing me. I love how you talked about how woman have calling to teach the children. And I learned a lot from this video. However 1 tiny thing I'd like to say is that I believe that woman in the Lord may be considered to be "sons" of God. The Biblical basis for this is...
    Just because a woman person may have an identity in Christ as a son of God (as Paul says neither male nor female), this transcendent reality is not a reason to pervert the natural order of things regarding natural gender. Paul is certainly not endorsing LGBT, etc. or same-sex marriage, and certainly not endorsing that slaves should not submit to their earthly master. Interestingly, I think Jesus is implying by saying that the sons of this age marry and 'are given' (women are given) in marriage, that a woman may be considered a "son of this age", and it really gets me thinking about what that word 'son' is being used to mean. It's not a natural gender thing:

    *[[https://www.biblegateway.com/passage/?search=Luke%2020%3A33-36&version=ESV][Luke 20:33-36]]* - In the resurrection, therefore, whose wife will the woman be? For the seven had her as wife. And Jesus said to them, The sons of this age marry and 'are given' (women are given) in marriage, but those who are considered worthy to attain to that age and to the resurrection from the dead *neither marry nor are given in marriage*, for they cannot die anymore, because they are equal to angels and are *sons of God, being sons of the resurrection*. (ESV)

...

So, it all starts here with
the foundation. We have to go to God's
order in creation in order to truly
understand this topic.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Genesis%202%3A18-22&version=ESV][Genesis 2:18-22]]* - Then the LORD God said, It is not good that the man should be alone; I will make him a helper fit for him. So out of the ground the LORD God formed every beast of the field and every bird of the heavens and brought them to the man to see what he would call them. And whatever the man called every living creature, that was its name. The man gave names to all livestock and to the birds of the heavens and to every beast of the field. But for Adam there was not found a helper fit for him. So the LORD God caused a deep sleep to fall upon the man, and while he slept took one of his ribs and closed up its place with flesh. And the rib that the LORD God had taken from the man he made into a woman and brought her to the man. (ESV)
#+END_QUOTE

That is why a man
leaves his father and mother and is
united to his wife and they become one
flesh. So a few key observations here we
have to see. Adam was created first then
Eve as his helper. That's the Hebrew
word Ezar. The term helper doesn't imply
inferiority. Right? God himself is
called our helper. So it's not that
woman is inferior to man. No, there is
just a created order. We see here that
in doing so, this is where we see the
establishment of this pattern of
complimentary roles from creation. Okay,
God is a God of _order_. There's a system
and Paul is going to specifically appeal
to this created order in his teaching
about church leadership. So if we want
to understand this topic, we have to go
back to the very beginning because we're
going to see it come to complete, you
know, just order in our understanding
because in 1 Timothy 2, let's look at
12-14, Paul is going to break this down.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%202%3A12-14&version=ESV][I Timothy 2:12-14]]* - I do not permit a woman to teach or to exercise authority over a man; rather, she is to remain quiet. For Adam was formed first, then Eve; and Adam was not deceived, but the woman was deceived and became a transgressor. (ESV)
#+END_QUOTE

This is what should make this case done and done.
We're going to dig in deeper to make
sure we're thoroughly understanding it
and looking at the counterarguments to
this and all of it. I do not permit a
woman to teach or to assume authority
over a man. Paul grounds his
instructions in creation order, not some
sort of cultural circumstance. He goes
all the way back to the very creation of
woman. We see here that his going back
to that and bringing it back to Adam and
Eve means that this wasn't just some
sort of like temporary who he was
talking to in that moment, but a
universal truth for the church
regardless of time, location, anything
else. Because the Greek word for
authority, authento, if I'm saying that
correctly, means to exercise dominion or
have authority over. Okay? "Teach", here,
refers to authoritative doctrinal
instruction in the church assembly. Yes,
are we all male, female, young, old,
, whatever? Are we all called to be
able to give an account for why we
believe what we believe? Yes,
absolutely. Do women have very specific
roles and callings? Yes, absolutely. And
we're going to get into that here in a
minute. But we're talking about
exercising dominion or having authority
over the /church/ as a group and teaching
being that authoritative doctrinal
instruction to the church assembly.
That's what we're talking about if we're
talking about pastor, right? This
role, this special designation,
okay. So, let's look at the principle of
headship before we get into the
qualifications for church leadership.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%2011%3A3&version=ESV][I Corinthians 11:3]]* - But I want you to understand that the head of every man is Christ, the head of a wife is her husband, and the head of Christ is God. (ESV)
#+END_QUOTE

What do we see here in this passage? Well, God
operates through ordered relationships.
He just does. He is a God of order.
There is a system. There is a process.
You see it from Genesis to Revelation
over and over and over and over again.
Okay? His created design is everywhere.
And we understand this because we
understand the need for good leadership
in order and system in our world. What
happens to a massive corporation when
their leadership goes off the rails and
is falling apart? The whole thing
crumbles and falls apart. So we
understand that here from a worldly
standpoint. Well, the only reason why it
exists is because God created it. We see
that 'headship' does not mean 'superiority'.
It's this feminist movement that
has rooted itself within the church that
we just want women to be able to take
over everything because feminists do not
want 'equality'. They want 'domination'. And
that has made its way into the church as
well. Saying that man is the head of
woman does not mean that he is /superior/,
because we also see that the head of
Christ is God. So how can Christ submit
to the Father yet be fully God Himself?
Right? It obviously isn't meaning
"superior to". This principle applies to
the church structure and family
relationships. A wife is subject to her
husband just as children are subject to
their parents. Okay? Again, proper order
makes a difference. Headship involves
responsibility and loving leadership,
not domination. Look at [[https://www.biblegateway.com/passage/?search=Ephesians%205%3A22-24&version=ESV][Ephesians 5:22-24]]
and 24. And we'll look at the marriage
parallel here.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Ephesians%205%3A22-24&version=ESV][Ephesians 5:22-24]]* - Wives, submit to your own husbands, as to the Lord. For the husband is the head of the wife even as Christ is the head of the church, his body, and is himself its Savior. Now as the church submits to Christ, so also wives should submit in everything to their husbands. (ESV)
#+END_QUOTE

So the husband wife relationship mirrors Christ
in the church. The study and
understanding of marriage in that
imagery of Christ in the church, a
husband and a wife. I mean it's it's
fascinating. Fascinating study. The same
principle of loving headship applies in
church governance. Submission is not
about capability or worth but about
God's design for order. And we have to
understand this when we look at this
topic. So what are the qualifications
for church leadership? Well, let's go to
1 Timothy, right? 3:1-7.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%203%3A1-7&version=ESV][I Timothy 3:1-7]]* - The saying is trustworthy: If anyone aspires to the office of overseer, he desires a noble task. Therefore an overseer must be above reproach, the husband of one wife, sober-minded, self-controlled, respectable, hospitable, able to teach, not a drunkard, not violent but gentle, not quarrelsome, not a lover of money. He must manage his own household well, with all dignity keeping his children submissive, for if someone does not know how to manage his own household, how will he care for God's church? He must not be a recent convert, or he may become puffed up with conceit and fall into the condemnation of the devil. Moreover, he must be well thought of by outsiders, so that he may not fall into disgrace, into a snare of the devil. (ESV)
#+END_QUOTE

What is one of the biggest
issues with the modern day church today
is that people in leadership, pastors of
churches are not staying true, time and
time again, to 1 Timothy 3, here. So many
times when you look at churches who have
gotten wonky, it's there's lots of
issues going on within. You can bring up
this passage here and go through it and
say, [are] your overseers, your pastors,
right, the leaders of the church, are
they walking in accordance to the
instruction that they are called to? And
9.99999 times out of 10, they are not.
And then everything is just off the
rails from there.
This is the core understanding of what
it means to be a pastor. That authority
position over the church body. The
qualifications here consistently use
masculine pronoun and references. So we
already see I do not permit a woman to
teach or hold authority over the church.
And then who /can/ hold authority over the
church? "He", "he", "he". Right? We constantly
see it is talking about a man because
he's already said this is not a place
for a woman, it is a place for a man. And
gave reasons why, but now we're
following this up, right? We're using
scripture to interpret scripture. If I
take scripture and put it through the
lens of more scripture, am I going to
come out with the same answer? That's
what we want to do. That's how we truly
discern. I don't want to just pick
things and make it say what I want it to
say. I want to take the understanding
that I have. I want to put it through
more filters of God's word and see if
the same understanding still comes out
at the end. Faithful to his wife.
Literally, it's a one woman man. If
that's one of the requirements, how
would women do that?
Because, if a woman is faithful to his
wife, I like how does that even work?
Family leadership is a prerequisite,
right? Managing his household well.
We're seeing here that these aren't just
cultural accommodations. They're
/spiritual/ qualifications. Let's go to
Titus chapter 1. Let's look at 5-9 about
appointing the elders. Okay.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Titus%201%3A5-9&version=ESV][Titus 1:5-9]]* - This is why I left you in Crete, so that you might put what remained into order, and appoint elders in every town as I directed you— if anyone is above reproach, the husband of one wife, and his children are believers and not open to the charge of debauchery or insubordination. For an overseer, as God's steward, must be above reproach. He must not be arrogant or quick-tempered or a drunkard or violent or greedy for gain, but hospitable, a lover of good, self-controlled, upright, holy, and disciplined. He must hold firm to the trustworthy word as taught, so that he may be able to give instruction in sound doctrine and also to rebuke those who contradict it. (ESV)
#+END_QUOTE

He writes
there, "The reason I left you in Cree
was that you might put in order what was
left unfinished and appoint elders in
every town as I directed you."

Remember, you go through the epistles, these
letters written by Paul, Peter, John,
James, right? You go through all these
different letters and you see time and
time again, what they were doing was
helping the early church understand how
to be the church, right? How to do these
different things. And so you see this
time and time again of them, "Hey,
remember this is what we were working
on. This is what I told you. This is
what you need to do. This is how you
deal with this problem. This is how you
put this together."

And so we take that
and what can we learn from that of how
this should be walked out here today. An
elder must be blameless, faithful to his
wife, a man whose children believe and
are not open to the charge of being wild
and disobedient. Okay, so we just saw
this up above in his letter to Timothy.
These are the pastoral epistles, right?

+ Just as a note :: It's obvious to me that satan has tried to ensnare me like [[https://www.biblegateway.com/passage/?search=1%20Timothy%203%3A7&version=ESV][I Tim 3:7]] mentions, maybe to prevent me from being used in such a way.

Literally written, how does the church
run? How does this work? And now here in
Titus, continuing on this, he's
repeating the same stuff, right? He's
saying the same thing just to a
different group of people at a different
time. But it's the same message.
Blameless, faithful to his wife whose
children believe and who are not open to
the charge of being wild and
disobedient. Because again, he should be
managing his household well. Therefore,
since an overseer manages God's
household, he must be blameless, not
overbearing, not quick-tempered, not
given to drunkenness, not violent, not
pursuing dishonest gain. Rather, he must
be hospitable, one who loves what is
good, who is self-controlled, upright,
holy, and disciplined. He must hold
firmly to the trustworthy message as it
has been taught, so that he can
encourage others by sound doctrine, and
_refute_ those who oppose it. Again, you
see the problem we have in the modern
church, so often, is that the appointed
elders, overseers, pastors are not
living these things out. That's where we
have problems. Every single time
leadership in church turns from the
direct calling of scripture to their
lives, the church starts to fall apart.
And that even includes those who refuse
to oppose false teaching. That's another
topic. I know you talk about false
teachers and people go, "Oh, you're just
being mean to them. Don't say anything
mean about anyone. The Lord will work it
out. We're supposed to be all loving...
Refute those who oppose it, right?

+ Amen :: Amen

Like sound doctrine, true teaching, that's
another big topic. You want to learn
more, leave me your comments and
questions, put your little fish emoji
because that's a big topic. But in this
appointing of elders that we see in
Titus, we see a consistent pattern here.
Again, same masculine language, same
family leadership requirements, it's
written to different churches in
different places, and he's I mean, these
letters are going out at various times.
So obviously, there's universal
application here. Not only is he
bringing it back to the creation of all
humankind, but he's telling everybody
the same thing regardless of where
they're at. Elders and overseers are the
same office. Okay? So, we see that in
Acts 20. You look at verse 17-28.
Elders, overseers, pastors, right? Those
holding positions of authority. That's
what we're talking about.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%2020%3A17-28&version=ESV][Acts 20:17-28]]* - Now from Miletus he sent to Ephesus and called the elders of the church to come to him. And when they came to him, he said to them: You yourselves know how I lived among you the whole time from the first day that I set foot in Asia, serving the Lord with all humility and with tears and with trials that happened to me through the plots of the Jews; how I did not shrink from declaring to you anything that was profitable, and teaching you in public and from house to house, testifying both to Jews and to Greeks of repentance toward God and of faith in our Lord Jesus Christ. And now, behold, I am going to Jerusalem, constrained by the Spirit, not knowing what will happen to me there, except that the Holy Spirit testifies to me in every city that imprisonment and afflictions await me. But I do not account my life of any value nor as precious to myself, if only I may finish my course and the ministry that I received from the Lord Jesus, to testify to the gospel of the grace of God. And now, behold, I know that none of you among whom I have gone about proclaiming the kingdom will see my face again. Therefore I testify to you this day that I am innocent of the blood of all of you, for I did not shrink from declaring to you the whole counsel of God. Pay careful attention to yourselves and to all the flock, in which the Holy Spirit has made you overseers, to care for the church of God, which he obtained with his own blood. (ESV)
#+END_QUOTE

Let's look at
some direct instructions about women in
the church. So, can women be pastors?
hold the authority, elders, overseers,
right up here. Well, clearly it's saying
no. So, what do the women do?

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%202%3A11-12&version=ESV][I Timothy 2:11-12]]* - Let a woman learn quietly with all submissiveness. I do not permit a woman to teach or to exercise authority over a man; rather, she is to remain quiet. (ESV)
#+END_QUOTE

And the feminist bone in every
single one of us that came from the
curse out of the garden where we would
desire to rule over our husbands just
lights up inside of us and makes us
women go, "Oof, this is my least
favorite verse in the entire Bible.
Let's pretend like it doesn't exist."
That's what happens so often. I get it.
But let's understand quiet and
submission. The Greek word here which I
am going to absolutely butcher if I try
to pronounce means quietness, peaceful
demeanor, not just "absolute silence" (to understand it as "absolute silence" would be not accurate).

Remember we talked about in should we
only be reading the King James version
Bible and understanding translations and
how this works and how it's a really
difficult process to like take a word
from one language that we don't actually
have an exact match for in ours. And so
we have to kind of like pick the best
thing. And that's why it's always best
to look at multiple translations to
really understand sometimes especially
for these tricky passages like how that
all works together. Quietness, peaceful
demeanor, which goes hand in hand with
this understanding of men are to hold
the authorative headship over the church
and women in their proper place under
that. So if I am learning in that proper
headship, I have a peaceful demeanor
about it. I'm not taking over that role,
right? I'm not coming in. We see the
same word used here for men in [[https://www.biblegateway.com/passage/?search=1%20Timothy%202%3A2&version=ESV][1 Timothy 2:2]]. 

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Timothy%202%3A2&version=ESV][I Timothy 2:2]]* - for kings and all who are in high positions, that we may lead a peaceful and quiet life, godly and dignified in every way. (ESV)
#+END_QUOTE

There is a peaceful demeanor that
we (women) bring, not one of authority, not one
of confrontation, not one of just
brashness, quietness, and peaceful
demeanor. Submission here refers to
recognizing God's established order.

...

The prohibition is
specifically about teaching men in the
church and exercising authority over
them. This is that key point here. 1 Corinthians 14, let's look at
the second half there, 33 and 35.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%2014%3A33-35&version=ESV][I Corinthians 14:33-35]]* - For God is not a God of confusion but of peace. As in all the churches of the saints, the women should keep silent in the churches. For they are not permitted to speak, but should be in submission, as the Law also says. If there is anything they desire to learn, let them ask their husbands at home. For it is shameful for a woman to speak in church. (ESV)
#+END_QUOTE

As in all the congregations of the Lord's
people, women should remain 'silent' in
the churches. They are not allowed to
speak, but must be in submission as the
law says. If they want to inquire about
something, they should ask their own
husbands at home. For it is disgraceful
for a woman to speak in the church. It's
got to be our feminist boned in us.
That's got to be our second least
favorite passage in the Bible, right?
What does that mean? Well, this follows
Paul's instructions about prophecy in
tongues. Okay? Silent here is relating
to judging the prophecies.

Women participated in worship, Absolutely.
Right. Go to [[https://www.biblegateway.com/passage/?search=1%20Corinthians%2011%3A5&version=ESV][1 Corinthians 11:5]].

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=1%20Corinthians%2011%3A5&version=ESV][I Corinthians 11:5]]* - but every wife who prays or prophesies with her head uncovered dishonors her head—it is the same as if her head were shaven. (ESV)
#+END_QUOTE

The issue is that authoritative evaluation
of the teaching. The role for coming in
with the authority and doing anything
within the body of the church is
reserved for the men. It is not the
women's role to come in with authority
over men in the church. So let's look at
the the counter-arguments here because
this is where people go whoa, whoa, whoa,
but what about, but what about, right? It
has said multiple times now I do not
permit a woman to teach, I do not permit
a woman to hold authority, I do not
permit a... right? We keep seeing that, just
read through them. And this is where
everybody comes in and goes well what
about well what about, well what about.
Well, let's look, let's see what about.
"These were just cultural restrictions
that this referred to them, it doesn't
apply now... things are different." That's
one argument we hear. So, let's
see, Paul's appealing to creation order,
right? We started with that. He's not
talking about cultural circumstances. If
he can bring it back to the very
creation of woman, then I think it
applies to us here today because we're
still created women, right?

 + Amen :: Amen

The same principles appear in multiple letters to
different churches, different locations,
different cultures, different times.
It's across the board. He does not
change even a little bit in what he's
saying. He's saying the same thing
repeated over and over and over again.

We have no textual indicators suggesting
that these were temporary instructions,
right? Other cultural practices like
head coverings, they're explicitly tied
to culture, but /these/ were tied to
creation. And so there's a big key
difference here that we see. Whenever we
read through the epistles, we read
through these letters, we have to
understand the context. And we do this,
you need to do this with all Scripture
and understanding the context. Who was
it written to? Why was it written? What
is the purpose? All scripture is useful
for teaching, okay? All scripture is
important and useful, but you have to
understand the context. So instead of
just putting yourself in whatever
position you want to, it's important to
understand /who/ was it written to, /why/
was it written, /what/ was the purpose,
and /how/ can I learn from this? And so we
have to understand that we can't just
take something and and make it be
'absolutely relevant to everything that I
want in every situation where I'm at
here today'. Reading through the letters
is just that you're reading through
someone else's mail. Now, yes, much of
it was written to the church as a whole
until the Lord returns and we are
reunited with him. This is instruction
and teaching for the church. But there
are some things that are directly
addressing situations and things that
were going on with those people at that
time because we're "reading somebody's mail". Okay?

Now, many of these letters
were going out to a certain church and
then saying, "Hey, continue passing them
around." Right? This is the early church
curriculum of how we church. Some things
are Paul making sure that somebody knows
he needs his winter coat and hey, when
you come down this way, make sure you
bring it with you. Okay? So there are
specific things included in these
letters in certain passages that are to
those people answering very real things
that they were facing. Some things are
more tied to the specific cultural
time-sensitive things that were going
on. Now we can still learn from them,
but it doesn't mean that it's going to
necessarily "apply" here in 2025 in modern
day America. I can learn from it because
all scripture is God breathed and usable
for teaching and reproof and all of the
stuff, that's fantastic. But not
everything is necessarily going to
connect to exactly what we're dealing
with today.

But you bet your bottom
dollar that if he is going back to the
very creation of a woman, that that's
something that's going to continue.

+ Amen :: Amen

Okay. If he keeps repeating the same
ideal about that's most likely important
for you and I here today. Okay. What
about the argument that women leaders in
scripture prove that women can be
pastors? People go, "Oh, well, we've had
many women in leadership roles in
scripture. So obviously that means that
women /can/ be pastors. Well, go to
Deborah, right? She's the one you hear
usually first and foremost. That's in
Judges 4. Let's look at 4 and 5. Now
Deborah, a prophet, the wife of Laped,
was leading Israel at that time. She
held court under the palm of Deborah
between Raman and Bethl in the hill
country of Ephereim. And the Israelites
went up to her to have their disputes
decided.

Deborah was placed into the
role of judge over Israel. This is back
during the time of the judges. The
reason why Deborah is one, that's a
whole another story that we can get
into. But Deborah was a judge over
Israel and not a church pastor. Okay?
They're not the same thing.

This was before the establishment of the church
in the order. They are removed from one
another by thousands of years. Her role
was civil in military leadership, not
church spiritual authority. Even she
deferred to Barack for military
leadership. Okay.

Can women be president, be queen, be what? Like sure,
yeah, those things can happen. That is
not church spiritual authority.

And so when we look to Deborah, yes, Deborah
was put in a role of leadership, but
that is not connected to thinking that
we can throw away everything we just
read as Paul was, you know, putting
together understanding of the headship
of the church and therefore make that
say that women can be like they're not
connected. It has nothing to do with
being a pastor or holding authority in a
church role here today. Just because
Deborah was a judge over Israel, they
don't connect.

What about Phoebe? We see her in Romans 16.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%2016%3A1-2&version=ESV][Romans 16:1-2]]* - I commend to you our sister Phoebe, a servant of the church at Cenchreae, that you may welcome her in the Lord in a way worthy of the saints, and help her in whatever she may need from you, for she has been a patron of many and of myself as well. (ESV)
#+END_QUOTE

Phoebe is an amazing case study. I love
the story of Phoebe. She was a deacon.
That means that she was literally a a
servant of the church here. That's not
an elder or a pastor. That is not a role
of authority over the church. Being a
deacon is different from being an elder
or an overseer. Phoebe was a very
successful businesswoman. She had plenty
of resources and she happily served the
church through her giving of her
resources. Use my home, right? We can
assume from her success that she had a
nice home. She had a lot of space. She
used what she had and was the benefactor
of many people. She took her worldly
success and poured it into the church
and said, "How can I serve here? How can
I do good for the the largecale cause
here of the church?" She was not the
pastor, right? She was not the the
overseer. She was not in this authority
role. Instead, she was one of the
ultimate servants, a deacon of the
church, being able to take what she had
that the Lord had blessed her with and
be a faithful steward to use what the
Lord entrusted to her in her earthly
success and pour it right back into the
needs of the church.

What about Priscilla? Priscilla is another amazing
one. Our time in ministry, my husband
and I literally called it A&P because we
were so inspired by the testimony here
of Aquilla and Priscilla. Go to [[https://www.biblegateway.com/passage/?search=Acts%2018%3A26&version=ESV][Acts 18:26]]. 

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Acts%2018%3A26&version=ESV][Acts 18:26]]* - He began to speak boldly in the synagogue, but when Priscilla and Aquila heard him, they took him and explained to him the way of God more accurately. (ESV)
#+END_QUOTE

We see here that
Priscilla taught alongside of her
husband. They worked together in
everything that they did. Aquill and
Priscilla, again, fascinating,
fascinating characters in scripture to
dig into. If you've ever watched the
movie um Paul, I think it's called like
Paul, an apostle of Christ, you see them
in it a lot. It is really cool to see
and kind of get that idea and that
understanding there of them, and they
taught alongside. But together, with her
husband in a private setting. Like she
wasn't co-pastor with her husband and
that's why I bring that up of our time
in ministry. Because, did I teach and work
and was I the helper to my husband
alongside of him throughout our time in
that? Absolutely, 1000%! I was never a
co-pastor. I was never in some sort of
authority role. My husband and his
associate pastor were the headship. Now,
me and the associate pastor's wife, we
were supports. We helped, but never ever
ever in any way, shape, or form in a
role of authority. And that's what we
see here with Priscilla. This wasn't
public church teaching or exercising
authority over men. Private instruction
is different from formal church
leadership. Should we as women be able
to have private instruction? Should we
be able to discuss why we believe what
we believe and how we understand it and
be able to give an account for what we
believe? Of course, absolutely. Every
single believer should be able to give
the gospel message, to be able to share
it with anyone they come across, to be
able to give an account for why they
believe the things that they believe and
share truth with those that the Lord
puts into their path. Amen. Amen. Amen.
I know I've talked about this before and
people go, "Oh, well, you're on YouTube,
so aren't you trying to be a pastor?"
Not in the slightest. Never, ever, ever
in a million years. I love that I've
been given a space here for the past
"nearly 8 years". My heart is really in
sharing with women. Over the years, a lot
of the the husbands have kind of come in
because we're talking about the home. It
is literally called "Heavenly Minded
Home", because I want to talk about things
that I'm going through that I'm learning
that I'm facing that I'm seeing through
my walk with the Lord, and share them
with you as a place here to say, hey,
you're watching this in your home, right?
I am in my home and I'm saying, "Hey, how
do we pour into our homes to be more
heavenly minded?" In no way shape or form
am I the authority on anything. I'm just
a little old housewife homeschool mom
wanting to dig into scripture and have
real conversations with friends that I
make here along the line and say, "How
do we do this? How do we build our homes
up? How do we tackle those difficult and
even messy topics that nobody else wants
to? How do we go to God's word?" Because
*that's* the authority, not anything of
me. And never in a million years are you
going to see me step into a church into
a role of authority and be teaching over
the men and putting myself in that role
because that's that's not where I'm to
be. And I want to be in accordance with
God's word, which means submitting to
his authority, His created order.

+ Amen :: Amen

What about seeing [[https://www.biblegateway.com/passage/?search=Galatians%203%3A28&version=ESV][Galatians 3:28]]? Some people
use this to say that this eliminates
role distinctions. Okay, [[https://www.biblegateway.com/passage/?search=Galatians%203%3A28&version=ESV][Galatians 3:28]]
says, "There is neither Jew nor Gentile,
neither slave nor free, nor is there
male and female, for you are all one in
Christ Jesus."

And people go, "Well, then why does it even matter what can
men do? What can women do? Like there's
no distinction between men and women, so
we can all do whatever we want to do."
Well, this verse is addressing salvation
and standing before God. He's saying
here that when we all stand before the
Lord, we're not going to be categorized,
oh, who came from the line of Judah, who
is a Gentile, get in your proper lines.
We're not going to say, oh, who who was,
you know, a slave and who was free, who
was male, who was female. Like, we don't
line up in boy girl lines at the pearly
gates to go in before the Lord in his
throne room. That's what he's talking
about there. He's not saying that there
is no difference between men and women.
There's no difference between Jew and
like Gentile. That's not what he's
saying. Equal worth doesn't mean
identical roles. Paul wrote both this
verse and [[https://www.biblegateway.com/passage/?search=1%20Timothy%202%3A12&version=ESV][1 Timothy 2:12]], right? So, how
did Paul talk so much about headship and
submission and men and women and
specific roles if he's also saying that
it doesn't matter if you're male or
female? Like that that just doesn't
check out.

Again, we can't take specific
verses to build up our case if they
don't hold up against the scrutiny of
being put through more scriptural
filters. Right?
Scripture interprets scripture. And so if you're going to
make a case off of a verse, but then
when adding in more verses, it falls
apart. Then that first case you made
doesn't hold up and so you can't keep
using it.

+ Amen :: Amen

What about the argument that
spiritual gifts trump role restrictions?
That's another one that I hear. We have
to understand that any spiritual gift
must be exercised within biblical
boundaries. If the spiritual gift you
are claiming is being used outside of
that or in objection to what the
boundaries are supposed to be, nope.
Nope. That's not how it works. We're
given very specific instruction to the
order and process of these things. I see
this all the time with people that
claim, you know, speaking in tongues.
And you're like, but if you're not using
it within the biblical boundaries, you
are discrediting your entire point there
of thinking you're doing what you're
doing because you've gone out of the
bounds of scripture how that's supposed
to work. Having a gift doesn't
automatically grant office or authority.
Nope. Many ways exist for women to use
teaching gifts appropriately. God's
gifting works within his established
order. He's never going to go against
his own word in something. So if what
you're doing, again, if you have a
point, but it doesn't hold up in the
total context of scripture, then we
don't change what we want it to be. We
change what we thought it was and align
ourselves to God's word.

+ Amen :: Amen

So all of this
to say, what is the role of women in the
church? I feel like we've made the first
part very clear. So what is the role of
women? Because people go, "What are
women what are women gonna do, right?
What's the point of women?" [[https://www.biblegateway.com/passage/?search=Titus%202%3A3-5&version=ESV][Titus 2:3-5]].

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Titus%202%3A3-5&version=ESV][Titus 2:3-5]]* - Older women likewise are to be reverent in behavior, not slanderers or slaves to much wine. They are to teach what is good, and so train the young women to love their husbands and children, to be self-controlled, pure, working at home, kind, and submissive to their own husbands, that the word of God may not be reviled. (ESV)
#+END_QUOTE

You guys know biblical
womanhood is like my favorite topic in
the whole wide world. We talk about it a
ton here. We talk about it even more
over on my other channel, Make
Femininity Great. Again, if you guys
haven't signed up over there, we've got
some really cool new stuff going on over
there for the women specifically, but we
see a very clear calling for what it
means to be a woman in the church here
today. Likewise, teach the older women
to be reverent in the way they live, not
to be slanders, addicted to much wine,
but to teach what is good. Then they can
urge the younger women to love their
husbands and children, to be
self-controlled and pure, to be busy at
home, to be kind, and to be subject to
their husbands so that no one will
malign the word of God. You want to know
what your role as a Christian woman is?
Come and join. It's a free study,
Biblical Womanhood. We go through every
single one of these verses in absolute
detail. Women are called to teach
specifically the women and children.
That is an immense honor to be given
that role and it is one that us ladies
need to start taking seriously. They
have very specific mentoring and
discipleship roles. Ladies, we need to be
living those out as Titus 2 women. And
that is absolutely my goal with what I
do here, what I do on my other few
channels. That's why we do what we do.
They're to pass on godly wisdom and
practical life skills.

Women have a huge calling and it is one that the enemy has
twisted for years and years and years
now. And it is one that our world is
crying out for today. And us ladies, we
need to get on it. We need to realize
God's design and desire for our lives.
And we need to start walking it out
because when we don't do those things,
we can literally be discrediting God's
word by our lives. And I know I don't
want to be doing that. [[https://www.biblegateway.com/passage/?search=Romans%2016%3A1-12&version=ESV][Romans 16:1-12]], we see women in ministry here.

#+BEGIN_QUOTE
  *[[https://www.biblegateway.com/passage/?search=Romans%2016%3A1-12&version=ESV][Romans 16:1-12]]* - I commend to you our sister Phoebe, a servant of the church in Cenchrea. Welcome her in the Lord in a manner worthy of the saints, and assist her with anything she may need from you. For she has been a great help to many people, including me. Greet Prisca and Aquila, my fellow workers in Christ Jesus, who have risked their lives for me. Not only I but all the churches of the Gentiles are grateful to them. Greet also the church that meets at their house. Greet my beloved Epenetus, who was the first convert to Christ in the province of Asia. Greet Mary, who has worked very hard for you. Greet Andronicus and Junia, my fellow countrymen and fellow prisoners. They are outstanding among the apostles, and they were in Christ before I was. Greet Ampliatus, my beloved in the Lord. Greet Urbanus, our fellow worker in Christ, and my beloved Stachys. Greet Apelles, who is approved in Christ. Greet those who belong to the household of Aristobulus. Greet Herodion, my fellow countryman. Greet those from the household of Narcissus who are in the Lord. Greet Tryphena and Tryphosa, women who have worked hard in the Lord. Greet my beloved Persis, who has worked very hard in the Lord. (engbsb2020eb)
#+END_QUOTE

The point of that, even though I
messed up all of the names, I'm so
sorry. I really am not great with names.
We see women in ministry over and over
and over again. Paul, who is saying, "I
do not permit a woman to teach." Right?
He's not just anti-woman. Oh, he's a
single guy. He hates women. He's just,
you know, toxic masculinity. That's what
so many people think. No, because he's
singing the praises of these women.
*Outstanding* among the apostles, *worked very hard* in the Lord, work very hard in
the Lord, my co-worker in Christ Jesus.
Right? He's praising these women in
ministry. Deacon ministry, which is
servant leadership, /very/ important in
the church from both the men and women.
Co-working in the gospel, hard work in
ministry, hospitality and support,
evangelism and missions. Is there a role
in a place for women? 1000%. It is just
not in the place of authority and
headship. What about Acts 16 when we see
Lydia's ministry? On the Sabbath we went
outside the city gate to the river where
we expected to find a place of prayer.
We sat down and began to speak to the
/women/ who had gathered there. One of
these listening was a woman from the
city of Thotyra named Lydia, a dealer in
purple cloth. She was a worshshiper of
God. The Lord opened her heart to
respond to Paul's message. When she and
the members of her household were
baptized, she invited us to her home.
Evangelistic heart and gathering others,
hospitality ministry, supporting the
apostolic work, leading her household to
faith. Here we saw Lydia, right? Another
woman, dealer in purple cloth. That
means she's got a good business going
on. Okay, she's got some money. She's
got some stuff. The Lord opens her
heart. She responds to Paul's message
and immediately says, "How can I serve
you? How can I use the resources the
Lord has entrusted to me, be a faithful
servant of the Lord, and now use that to
pour into the church?" Do women have
amazing, wonderful roles? Yes. But to
submit to God's order, they are not
roles of authority. And so I do have
some resources again looking at
practical application from the church
perspective, women's perspective, men's
perspective across the board. I'm going
to put additional resources, sermons,
things like that linked into this
resource so that way you guys can go and
dig in deeper to all of that. It's
absolutely all linked down below in the
description.

- [[https://www.youtube.com/playlist?list=PL3e3aMoZOIhXYdxr_qS7QAWhHYcwKqgy5][youtube.com: Rooted in Titus - A Summer of Biblical Womanhood]]
- [[https://hmh.myflodesk.com/womenpastors][hmh.myflodesk.com: Can women be pastors?]]

We have to understand proper headship and order. When we talk
about these things, we have to look not
at the lens of our own thoughts and
opinions, but God's word, discerning
God's word.

And so, friends, I know that
these fishbowl topics have been a little
bit longer of videos, but I want to make
sure that we are being thorough. If we
are going to stumble upon various topics
and go, man, how do I discern that one?
Right? How do I work through that? Well,
we're going to go to God's word. Because
if we want to truly build up
heavenly-minded homes, we have to be
people that are living as citizens of
heaven in /alignment/ to what God calls us
to be. And the /only/ way to know what
that is is to go to his Wordw to work
through itw bit by bit by bit, making
sure that if I see this over here and I
go, "Okay, that makes sense. Well, let
me put it through the rest of scripture
and say, okay, when I put it with those
weights and balances, does it still
check out? Does that still make sense?"

Well, we saw Paul saying the same thing
over and over and over and over and over
again. We took from Old Testament, New
Testament, put it through the different
things and said, "Okay, does this make
sense?" Well, yeah. We see creation, we
see that the role of judge was not the
role of pastor, we see that what women
in the New Testament church were doing,
right? We kind of put it through all
these different lenses and go,
"Okay, now we see where that checks out.
Can women be pastors?" No. Women cannot
be in any role that puts them in an
authority place above the church.

...

Do women have very specific roles and callings? Yes, we do.
And there is amazing beauty and blessing
in all that. Again, check out biblical
womanhood. Come and join our study we're
doing right now. We're covering lots of
this stuff in its practical application
each and every day. But we're not in a
place of headship. We're not in a place
of authority.

We are very much called as
Titus 2 women to be pouring into the
other women, to be pouring into the
children, the future generations, the
future of the church to come. How about
instead of being so focused on a role
that isn't ours, and allowing the enemy
to keep that thing in you, well, I want
to be a pastor. Well, I want this. I
want women to be in charge of
everything. How about instead we know
where our role is, and we live it out to
its fullest, bringing God all glory in
the process.

+ Amen :: Amen
